import Head from 'next/head'

import Link from 'next/link'

const Header = () => {
  const styles = {}
  return (
    <>
      <Head>
        <title>Marketplace Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.logo}> </div>
        <div className={styles.menu}>
          <Link href="/">Hackathon</Link>
          <Link href="/news">News</Link>
        </div>
      </header>
    </>
  )
}

export default Header
